// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbQ-VDys5Fb8EeY9MgmbOWeEf5v-XQtto',
    appId: '1:545410993533:web:3c33a0a0607a0526e11014',
    messagingSenderId: '545410993533',
    projectId: 'flutter-chat-app-94384',
    authDomain: 'flutter-chat-app-94384.firebaseapp.com',
    storageBucket: 'flutter-chat-app-94384.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzKf9fYqq7u7tfV8dnVcKiLKDCUnk4HdQ',
    appId: '1:545410993533:android:fa8083dd0678e5e0e11014',
    messagingSenderId: '545410993533',
    projectId: 'flutter-chat-app-94384',
    storageBucket: 'flutter-chat-app-94384.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCICTex6HoZAx0_CflcWvyZK_kLwAsupw',
    appId: '1:545410993533:ios:727cd673c3c73722e11014',
    messagingSenderId: '545410993533',
    projectId: 'flutter-chat-app-94384',
    storageBucket: 'flutter-chat-app-94384.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCICTex6HoZAx0_CflcWvyZK_kLwAsupw',
    appId: '1:545410993533:ios:01ff6f0685f28022e11014',
    messagingSenderId: '545410993533',
    projectId: 'flutter-chat-app-94384',
    storageBucket: 'flutter-chat-app-94384.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
