// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByYxESu5pgKRUMVWd_Vm2u2abhmEtxZwk',
    appId: '1:358763826402:web:1a6d67e226507da300a2bb',
    messagingSenderId: '358763826402',
    projectId: 'whatsapp-backen-57fff',
    authDomain: 'whatsapp-backen-57fff.firebaseapp.com',
    storageBucket: 'whatsapp-backen-57fff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxaWOJazP23vw5YRwRZZKnt2VBRprcxqs',
    appId: '1:358763826402:android:2c550a328b33a8f400a2bb',
    messagingSenderId: '358763826402',
    projectId: 'whatsapp-backen-57fff',
    storageBucket: 'whatsapp-backen-57fff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKdsYazWYVzig9Y2l7H14vchKJJWRgbug',
    appId: '1:358763826402:ios:313f283e268cf93b00a2bb',
    messagingSenderId: '358763826402',
    projectId: 'whatsapp-backen-57fff',
    storageBucket: 'whatsapp-backen-57fff.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKdsYazWYVzig9Y2l7H14vchKJJWRgbug',
    appId: '1:358763826402:ios:2ce0179344512fd800a2bb',
    messagingSenderId: '358763826402',
    projectId: 'whatsapp-backen-57fff',
    storageBucket: 'whatsapp-backen-57fff.appspot.com',
    iosBundleId: 'com.example.whatsapp.RunnerTests',
  );
}
