// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyj6aL9Dfby1JKRdcuHOQsYHZMQuNGE1k',
    appId: '1:697595140701:web:9ec4c3d1db063ec857cbb4',
    messagingSenderId: '697595140701',
    projectId: 'flutter-prep-6f6b9',
    authDomain: 'flutter-prep-6f6b9.firebaseapp.com',
    databaseURL: 'https://flutter-prep-6f6b9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-6f6b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkGbq7FB41Tr-WoPPc5mIqaZdYcxML_pM',
    appId: '1:697595140701:android:98dc39273989cf6657cbb4',
    messagingSenderId: '697595140701',
    projectId: 'flutter-prep-6f6b9',
    databaseURL: 'https://flutter-prep-6f6b9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-6f6b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0V3fOcjfMDbfOuFSX7n-vDZLt-fukj_4',
    appId: '1:697595140701:ios:7864e42ee86e463957cbb4',
    messagingSenderId: '697595140701',
    projectId: 'flutter-prep-6f6b9',
    databaseURL: 'https://flutter-prep-6f6b9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-6f6b9.appspot.com',
    iosBundleId: 'com.example.fbAuthBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0V3fOcjfMDbfOuFSX7n-vDZLt-fukj_4',
    appId: '1:697595140701:ios:5079449729d1968457cbb4',
    messagingSenderId: '697595140701',
    projectId: 'flutter-prep-6f6b9',
    databaseURL: 'https://flutter-prep-6f6b9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-6f6b9.appspot.com',
    iosBundleId: 'com.example.fbAuthBloc.RunnerTests',
  );
}
