// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJjBTCFbwgVC3qrRrL0EbRhmfRAOgC5Y4',
    appId: '1:546679391159:web:1b5686f947d469dddc9e32',
    messagingSenderId: '546679391159',
    projectId: 'ecommerceapp-67761',
    authDomain: 'ecommerceapp-67761.firebaseapp.com',
    storageBucket: 'ecommerceapp-67761.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjMkUhbC8pzGFrTvI-4uF-NhBBlRgSNSQ',
    appId: '1:546679391159:android:70909b8a9b3f1a72dc9e32',
    messagingSenderId: '546679391159',
    projectId: 'ecommerceapp-67761',
    storageBucket: 'ecommerceapp-67761.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB86Ujqe7Pj2oXG5An7RUG2BVeMX1dVZKk',
    appId: '1:546679391159:ios:02e2223659a96fc1dc9e32',
    messagingSenderId: '546679391159',
    projectId: 'ecommerceapp-67761',
    storageBucket: 'ecommerceapp-67761.appspot.com',
    androidClientId: '546679391159-4bq29rvgk69l5e65ph2ur5rc67ecapnp.apps.googleusercontent.com',
    iosClientId: '546679391159-l2d5s25jt2sfitnai0pdc74tkml55603.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB86Ujqe7Pj2oXG5An7RUG2BVeMX1dVZKk',
    appId: '1:546679391159:ios:2fa45c94b475e4bbdc9e32',
    messagingSenderId: '546679391159',
    projectId: 'ecommerceapp-67761',
    storageBucket: 'ecommerceapp-67761.appspot.com',
    androidClientId: '546679391159-4bq29rvgk69l5e65ph2ur5rc67ecapnp.apps.googleusercontent.com',
    iosClientId: '546679391159-8dqbde20mvo6r6bnvhehv8l76vvhft8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceFirebase.RunnerTests',
  );
}
