// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6yPYIt6KUyKsNmA29oPtNZNTWwt64qZs',
    appId: '1:85384903127:web:34795302a42cff37bab392',
    messagingSenderId: '85384903127',
    projectId: 'instagram-flutter-d6f56',
    authDomain: 'instagram-flutter-d6f56.firebaseapp.com',
    storageBucket: 'instagram-flutter-d6f56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXYmTJ7Tul3aFPWFtFlv0Dvqqyp9AE9kA',
    appId: '1:85384903127:android:c9199f5350ddba02bab392',
    messagingSenderId: '85384903127',
    projectId: 'instagram-flutter-d6f56',
    storageBucket: 'instagram-flutter-d6f56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPEUW9rdVCB7DnZNX1Dc0QpYsbL3v1Mwk',
    appId: '1:85384903127:ios:949ab0e77bd2a64bbab392',
    messagingSenderId: '85384903127',
    projectId: 'instagram-flutter-d6f56',
    storageBucket: 'instagram-flutter-d6f56.appspot.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPEUW9rdVCB7DnZNX1Dc0QpYsbL3v1Mwk',
    appId: '1:85384903127:ios:59ab938162ea64e9bab392',
    messagingSenderId: '85384903127',
    projectId: 'instagram-flutter-d6f56',
    storageBucket: 'instagram-flutter-d6f56.appspot.com',
    iosBundleId: 'com.example.instagramFlutter.RunnerTests',
  );
}
