// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSCUMon2T9T8On6wznA8x7ARRJeCD2mCs',
    appId: '1:844096928214:web:d6d7f0b72a5a3b90284c77',
    messagingSenderId: '844096928214',
    projectId: 'fooddelivery-e552f',
    authDomain: 'fooddelivery-e552f.firebaseapp.com',
    storageBucket: 'fooddelivery-e552f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3arsY3zN3C47ufGtRnSDDAW79NkGhzYU',
    appId: '1:844096928214:android:e364823f7afbf361284c77',
    messagingSenderId: '844096928214',
    projectId: 'fooddelivery-e552f',
    storageBucket: 'fooddelivery-e552f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8pivi4rRQ74LmSxBinfpsslduzNzAh1Q',
    appId: '1:844096928214:ios:e3b82cfcf0f99477284c77',
    messagingSenderId: '844096928214',
    projectId: 'fooddelivery-e552f',
    storageBucket: 'fooddelivery-e552f.appspot.com',
    iosBundleId: 'com.example.firebaseFoodDeliveryEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8pivi4rRQ74LmSxBinfpsslduzNzAh1Q',
    appId: '1:844096928214:ios:195f6f75eba36a87284c77',
    messagingSenderId: '844096928214',
    projectId: 'fooddelivery-e552f',
    storageBucket: 'fooddelivery-e552f.appspot.com',
    iosBundleId: 'com.example.firebaseFoodDeliveryEcommerce.RunnerTests',
  );
}
