// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-viUVSgzYmp5SKzJTIK-B9v7EeYB0D0A',
    appId: '1:284828373473:web:93dd9cd4dbdf37bab302a0',
    messagingSenderId: '284828373473',
    projectId: 'flutter-video-audio-chat-c4081',
    authDomain: 'flutter-video-audio-chat-c4081.firebaseapp.com',
    storageBucket: 'flutter-video-audio-chat-c4081.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6SdTRWd-FlxlWQz-8Gl7rIC2k_8qJMk8',
    appId: '1:284828373473:android:809136313c646204b302a0',
    messagingSenderId: '284828373473',
    projectId: 'flutter-video-audio-chat-c4081',
    storageBucket: 'flutter-video-audio-chat-c4081.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrZ1QNuSubx0pWso0usawQ2kAc9CfbCa4',
    appId: '1:284828373473:ios:3d0dcd8d5562cbbdb302a0',
    messagingSenderId: '284828373473',
    projectId: 'flutter-video-audio-chat-c4081',
    storageBucket: 'flutter-video-audio-chat-c4081.appspot.com',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrZ1QNuSubx0pWso0usawQ2kAc9CfbCa4',
    appId: '1:284828373473:ios:279ab2f73e0b5896b302a0',
    messagingSenderId: '284828373473',
    projectId: 'flutter-video-audio-chat-c4081',
    storageBucket: 'flutter-video-audio-chat-c4081.appspot.com',
    iosBundleId: 'com.example.chatty.RunnerTests',
  );
}
