name: chatty
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  flutter_screenutil: ^5.9.0
  pull_to_refresh: ^2.0.0
  fluttertoast: ^8.2.4
  flutter_easyloading: ^3.0.5
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  crypto: ^3.0.3
  webview_flutter: ^4.5.0
  loading_animations: ^2.2.0
  share: ^2.0.4
  device_info: ^2.0.3
  package_info_plus: ^5.0.1
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  sentry: ^7.16.0
  uni_links: ^0.5.1
  dots_indicator: ^3.0.0
  google_sign_in: ^6.2.1
  firebase_core: ^2.25.3
  firebase_messaging: ^14.7.14
  firebase_in_app_messaging: ^0.7.4+12
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.15.3
  firebase_storage: ^11.6.4
  location: ^5.0.3
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  flutter_facebook_auth: ^6.0.4
  sqflite: ^2.3.2
  flutter_verification_code: ^1.1.7
  agora_rtc_engine: ^6.2.6
  just_audio: ^0.9.36
  flutter_local_notifications: ^16.3.2
  url_launcher: ^6.2.4
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/Sound_Horizon.mp3
    - assets/audio_mixing/Agora.io-Interactions.mp3
    - assets/agora-logo.png
    - assets/dang.mp3
    - assets/ding.mp3
    - assets/gif.gif
    - assets/jpg.jpg
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400 # normal
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf