// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAah9o_qp8TLDNPrx7pKEPoAlSgfEoyrrE',
    appId: '1:214445341514:web:d70b8919b35fbccebedfb3',
    messagingSenderId: '214445341514',
    projectId: 'easyshopping-362a3',
    authDomain: 'easyshopping-362a3.firebaseapp.com',
    storageBucket: 'easyshopping-362a3.appspot.com',
    measurementId: 'G-01Y8VR2SS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU2BcQXb6j9pJpKvBqHdMaKUKNX9l9B_Y',
    appId: '1:214445341514:android:c2ff9c8f6bbfc2f9bedfb3',
    messagingSenderId: '214445341514',
    projectId: 'easyshopping-362a3',
    storageBucket: 'easyshopping-362a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-w5D5md2tIqjQkunEk_0Wik8bTzreS5w',
    appId: '1:214445341514:ios:95372a59da0d4645bedfb3',
    messagingSenderId: '214445341514',
    projectId: 'easyshopping-362a3',
    storageBucket: 'easyshopping-362a3.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-w5D5md2tIqjQkunEk_0Wik8bTzreS5w',
    appId: '1:214445341514:ios:fc0477599428a4fbbedfb3',
    messagingSenderId: '214445341514',
    projectId: 'easyshopping-362a3',
    storageBucket: 'easyshopping-362a3.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseEcommerce.RunnerTests',
  );
}
